/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.semantic.swing.facet;

import com.semantic.lucene.util.IFieldProperty;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import org.apache.lucene.facet.FacetResult;
import org.apache.lucene.facet.LabelAndValue;

/**
 *
 * @author Christian Plonka (cplonka81@gmail.com)
 */
public class FacetFieldPanel extends JPanel {

    private final IFieldProperty def;

    public FacetFieldPanel(IFieldProperty def) {
        super();
        this.def = def;
        initComponents();
        jlTitle.setText(def.getName());
    }

    public IFieldProperty getDef() {
        return def;
    }

    public void setResult(FacetResult result, List<String> selectedLabels) {
        jpContent.removeAll();
        if (result != null) {
            for (LabelAndValue lv : result.labelValues) {
                JCheckBox cb = new JCheckBox(String.format("%s [%s]", lv.label, lv.value));
                cb.setSelected(selectedLabels.contains(lv.label));
                cb.putClientProperty("select_label", lv.label);
                jpContent.add(cb);
            }
        }
    }

    public String[] getSelectedLabels() {
        List<String> ret = new ArrayList<>();
        for (Component cmp : jpContent.getComponents()) {
            if (cmp instanceof JCheckBox) {
                JCheckBox cb = (JCheckBox) cmp;
                if (cb.isSelected()) {
                    ret.add(cb.getClientProperty("select_label").toString());
                }
            }
        }
        return ret.toArray(new String[ret.size()]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jpContent = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jlTitle.setBackground(new java.awt.Color(153, 153, 153));
        jlTitle.setText("jLabel1");
        jlTitle.setOpaque(true);
        add(jlTitle, java.awt.BorderLayout.NORTH);

        jpContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jpContent.setLayout(new javax.swing.BoxLayout(jpContent, javax.swing.BoxLayout.PAGE_AXIS));
        add(jpContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpContent;
    // End of variables declaration//GEN-END:variables
}
