/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IndexingPanel.java
 *
 * Created on 14.11.2011, 10:09:01
 */
package com.semantic.swing.preferences;

import static com.semantic.swing.MainFrame.*;

/**
 *
 * @author Christian Plonka (cplonka81@gmail.com)
 */
class IndexingPanel extends javax.swing.JPanel {

    /** Creates new form IndexingPanel */
    public IndexingPanel() {
        initComponents();
        initOwnComponents();
    }

    private void initOwnComponents() {
        checkColor.setSelected(PREF.getBoolean(KEY_IMAGE_COLOR_CLASSIFICATION, false));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledSeparator1 = new org.jdesktop.swingx.JXTitledSeparator();
        checkColor = new javax.swing.JCheckBox();

        jXTitledSeparator1.setTitle("Image Classification");

        checkColor.setText("Create Color-Index (needs reindex) - time intensive task");
        checkColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkColorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(checkColor))
                    .add(jXTitledSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jXTitledSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(checkColor)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkColorActionPerformed
        PREF.putBoolean(KEY_IMAGE_COLOR_CLASSIFICATION, checkColor.isSelected());
    }//GEN-LAST:event_checkColorActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkColor;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator1;
    // End of variables declaration//GEN-END:variables
}
