/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreferencesPanel.java
 *
 * Created on 04.11.2011, 16:04:17
 */
package com.semantic.swing.preferences;

import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Christian Plonka (cplonka81@gmail.com)
 */
public class PreferencesPanel extends javax.swing.JPanel implements ListSelectionListener {

    private Map<String, JComponent> panels = new HashMap<String, JComponent>();
    private String[] order = {"General", "Apperance", "Indexing"};

    /** Creates new form PreferencesPanel */
    public PreferencesPanel() {
        initComponents();
        initOwnComponents();
    }

    private void initOwnComponents() {
        panels.put(order[0], new GeneralPanel());
        panels.put(order[1], new AppearancePanel());
        panels.put(order[2], new IndexingPanel());
        /* add to cardlayout */
        DefaultListModel listModel = new DefaultListModel();
        for (String value : order) {
            listModel.addElement(value);
            optionView.add(panels.get(value), value);
        }
        optionList.setModel(listModel);
        optionList.addListSelectionListener(this);
        optionList.setSelectedIndex(0);
    }

    @Override
    public void valueChanged(ListSelectionEvent lse) {
        if (!lse.getValueIsAdjusting()) {
            showCard(order[optionList.getSelectedIndex()]);
        }
    }

    private void showCard(String id) {
        ((CardLayout) optionView.getLayout()).show(optionView, id);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        optionList = new javax.swing.JList();
        optionScroll = new javax.swing.JScrollPane();
        optionView = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        controlView.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 130));

        optionList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(optionList);

        controlView.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(controlView, java.awt.BorderLayout.WEST);

        optionScroll.setBorder(null);

        optionView.setPreferredSize(new java.awt.Dimension(350, 300));
        optionView.setLayout(new java.awt.CardLayout());
        optionScroll.setViewportView(optionView);

        add(optionScroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList optionList;
    private javax.swing.JScrollPane optionScroll;
    private javax.swing.JPanel optionView;
    // End of variables declaration//GEN-END:variables
}